name: Create UPM Branch
on: 
  create:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create Branch
        if: github.event.ref_type == 'tag'
        run: |
          echo 'Creating UPM release branch'
          git branch -d ${{env.UPM_BRANCH_NAME}} &> /dev/null || echo ${{env.UPM_BRANCH_NAME}} branch not found
          git subtree split -P "$PKG_ROOT" -b ${{env.UPM_BRANCH_NAME}}
          git checkout ${{env.UPM_BRANCH_NAME}}
          git push -f -u origin ${{env.UPM_BRANCH_NAME}}
    env:
      PKG_ROOT: Assets/Gemserk.SelectionHistory
      TAG_NAME: ${{github.event.ref}}
      UPM_BRANCH_NAME: com.gemserk.selectionhistory-$TAG_NAME